# General Application Configuration
appName: predict-diabetes-app
appVersion: v2
containerName: predict-diabetes-app
replicaCount: 1

# Image Configuration
image:
  repository: prashi2301/predict_diabetes_app
  tag: 1.0.0

# Container Port Configuration
containerPort: 5001

# Service Configuration
service:
  port: 80  # Define the port for the service here

# Service Account Configuration
serviceAccount:
  create: true  # Set to 'true' to create a service account, 'false' to not create one
  name: predict-diabetes-service-account  # Name for the service account, optional

# Ingress Configuration
ingress:
  enabled: true  # Set to 'true' to enable ingress, 'false' to disable it

# Autoscaling Configuration
autoscaling:
  enabled: true  # Set to 'true' to enable autoscaling, 'false' to disable it
  # Optional: Add other autoscaling settings as needed
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
