apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-diabetes-app
  labels:
    app: predict-diabetes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predict-diabetes-app
  template:
    metadata:
      labels:
        app: predict-diabetes-app
    spec:
      containers:
      - name: predict-diabetes-app
        image: prashi2301/predict_diabetes_app:1.0.0
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: predict-diabetes-service
spec:
  selector:
    app: predict-diabetes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer